#!/bin/bash

./prepare_dtb

( cd ../../../.. ; \
  ./compile.sh \
  	BOARD=mksklipad50 \
  	BRANCH=current \
	RELEASE=bookworm \
	BUILD_MINIMAL=no \
	BUILD_DESKTOP=no \
	BSPFREEZE=yes \
	KERNEL_CONFIGURE=no )
