#!/bin/bash

INPUTFILE=klipad50tpl.dts
REALNAME=rk3328-mksklipad50.dts
UBOOTPATCH=02-rk3328-mksklipad50-add-uboot-dts.patch

# ---- COMMON: split INPUTFILE into "uboot-only" and "kernel-only"  files ----

strip_parts() {
  mark=$1
  # remove all lines between "---FOO-start---" and "---FOO-end---" markers
  awk '/\/\/---'$mark'-end---/{f=0} !f{print} /\/\/---'$mark'-start---/{f=1}' $INPUTFILE \
    | sed "/^\/\/-/d"
    # strip all comment lines beginning with "//-" (keeps normal "//" comments)
}

ONLY_KERNEL_TMP=.only_kernel.dts
ONLY_UBOOT_TMP=.only_uboot.dts

strip_parts uboot  > $ONLY_KERNEL_TMP
strip_parts kernel > $ONLY_UBOOT_TMP

# ---- copy "kernel-only" file into KERNELDTB directory ----

# current
KERNELDTB=../../../kernel/archive/rockchip64-6.12/dt/
cp -L $ONLY_KERNEL_TMP $KERNELDTB/$REALNAME

# edge
KERNELDTB=../../../kernel/archive/rockchip64-6.13/dt/
cp -L $ONLY_KERNEL_TMP $KERNELDTB/$REALNAME

# ---- generate patch from "uboot-only" file ----

DIFFDIR="arch/arm/dts"
DIFFDIR_A="a/$DIFFDIR"
DIFFDIR_B="b/$DIFFDIR"

[ -d .diffdir ] && rm -rf .diffdir
mkdir .diffdir
cd .diffdir

mkdir -p $DIFFDIR_A
mkdir -p $DIFFDIR_B
cp ../$ONLY_UBOOT_TMP $DIFFDIR_B/$REALNAME

echo "From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001">../$UBOOTPATCH
echo "From: Thorsten Maerz <info@netztorte.de>">>../$UBOOTPATCH
#echo "Date: Thu, 30 Jan 2025 15:00:00 +0000">>../$UBOOTPATCH
echo "Date: $(date --rfc-2822)">>../$UBOOTPATCH
echo "Subject: feat: Add u-boot dts for MKSKLIPAD50 board">>../$UBOOTPATCH
echo "---">>../$UBOOTPATCH
echo >>../$UBOOTPATCH
echo "diff --git $DIFFDIR_A/$REALNAME $DIFFDIR_B/$REALNAME">>../$UBOOTPATCH
diff -uN $DIFFDIR_A/$REALNAME $DIFFDIR_B/$REALNAME>>../$UBOOTPATCH

cd ..
rm -rf .diffdir
